runtime: python39
entrypoint: gunicorn -b :$PORT --chdir app/ app.wsgi:application
env_variables:
    APPENGINE_URL: kakaocall-0929.du.r.appspot.com
    GOOGLE_CLOUD_PROJECT: kakaocall-0929

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

