# Generated by Django 4.1 on 2022-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=32)),
                ('last', models.CharField(max_length=32)),
                ('born', models.CharField(max_length=32)),
            ],
        ),
    ]
